import { Puzzle } from './types';

export const PUZZLES: Record<string, Puzzle[]> = {
  logic: [
    {
      id: 1,
      category: 'logic',
      difficulty: 'easy',
      title: 'As Três Caixas',
      description: 'Três caixas têm etiquetas TROCADAS: "OURO", "PRATA" e "CARVÃO".\n\nVocê retira um item da caixa "CARVÃO" e é ouro.\n\nO que está na caixa "OURO"?',
      hint: 'Todas as etiquetas estão erradas. Se tirou ouro da caixa "CARVÃO", essa caixa contém ouro, não carvão.',
      answer: 'prata',
      options: ['Ouro', 'Prata', 'Carvão'],
      answerType: 'multiple',
      timeLimit: 60,
      points: 100,
    },
    {
      id: 2,
      category: 'logic',
      difficulty: 'easy',
      title: 'Ovelhas do Fazendeiro',
      description: 'Um fazendeiro tem 17 ovelhas.\n\nTodas menos 9 morrem.\n\nQuantas ovelhas restam?',
      hint: '"Todas menos 9" significa que exatamente 9 sobrevivem.',
      answer: '9',
      answerType: 'text',
      timeLimit: 45,
      points: 100,
    },
    {
      id: 3,
      category: 'logic',
      difficulty: 'medium',
      title: '28 Dias',
      description: 'Quantos meses do ano têm 28 dias?',
      hint: 'Pense bem — todos os meses têm pelo menos 28 dias...',
      answer: '12',
      options: ['1', '2', '7', '12'],
      answerType: 'multiple',
      timeLimit: 60,
      points: 200,
    },
    {
      id: 4,
      category: 'logic',
      difficulty: 'medium',
      title: 'O Médico',
      description: 'Um médico tem um irmão médico.\n\nEsse irmão não tem nenhum irmão.\n\nComo isso é possível?',
      hint: 'Irmão e irmã são coisas diferentes...',
      answer: 'o médico é uma mulher',
      options: ['São gêmeos idênticos', 'O médico é uma mulher', 'Um deles é adotado', 'É impossível'],
      answerType: 'multiple',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 5,
      category: 'logic',
      difficulty: 'hard',
      title: 'A Ponte no Escuro',
      description: 'Quatro hackers cruzam uma ponte às escuras com 1 tocha. Máx. 2 por vez. Velocidades: A=1min, B=2min, C=5min, D=10min.\n\nQual o tempo mínimo para todos cruzarem?',
      hint: 'A+B cruzam (2min). A volta (1min). C+D cruzam (10min). B volta (2min). A+B cruzam (2min). Total: 17min.',
      answer: '17 minutos',
      options: ['15 minutos', '17 minutos', '19 minutos', '21 minutos'],
      answerType: 'multiple',
      timeLimit: 120,
      points: 300,
    },
  ],
  cipher: [
    {
      id: 6,
      category: 'cipher',
      difficulty: 'easy',
      title: 'Caesar Code',
      description: 'Decifre o código César com chave +3.\nCada letra foi avançada 3 posições no alfabeto.\n\n[ F  B  E  H  U ]',
      hint: 'F-3=C, B-3=Y, E-3=B, H-3=E, U-3=R',
      answer: 'cyber',
      answerType: 'text',
      timeLimit: 60,
      points: 100,
    },
    {
      id: 7,
      category: 'cipher',
      difficulty: 'easy',
      title: 'ROT13',
      description: 'Decifre usando ROT13.\nCada letra é rotacionada 13 posições no alfabeto.\n\n[ C  H  M  M  Y  R ]',
      hint: 'ROT13 é sua própria inversa. C(2)+13=P(15), H(7)+13=U(20)...',
      answer: 'puzzle',
      answerType: 'text',
      timeLimit: 60,
      points: 100,
    },
    {
      id: 8,
      category: 'cipher',
      difficulty: 'medium',
      title: 'Código Atbash',
      description: 'Decifre o código Atbash.\nA↔Z, B↔Y, C↔X, D↔W, ...\n\n[ S  Z  X  P ]',
      hint: 'S(18)↔H(7), Z(25)↔A(0), X(23)↔C(2), P(15)↔K(10)',
      answer: 'hack',
      answerType: 'text',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 9,
      category: 'cipher',
      difficulty: 'medium',
      title: 'A=1, Z=26',
      description: 'Cada número representa uma letra (A=1, B=2 ... Z=26).\n\n[ 8 - 1 - 3 - 11 - 5 - 18 ]',
      hint: '8=H, 1=A, 3=C, 11=K, 5=E, 18=R',
      answer: 'hacker',
      answerType: 'text',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 10,
      category: 'cipher',
      difficulty: 'hard',
      title: 'Vigenère',
      description: 'Cifra de Vigenère com chave "KEY".\nDecifre a mensagem:\n\n[ W  E  R  B  M  V ]',
      hint: 'W-K=M, E-E=A, R-Y=T, B-K=R, M-E=I, V-Y=X',
      answer: 'matrix',
      answerType: 'text',
      timeLimit: 120,
      points: 300,
    },
  ],
  pattern: [
    {
      id: 11,
      category: 'pattern',
      difficulty: 'easy',
      title: 'Potências de 2',
      description: 'Qual é o próximo número?\n\n2  →  4  →  8  →  16  →  ___',
      hint: 'Cada número é o dobro do anterior.',
      answer: '32',
      answerType: 'text',
      timeLimit: 45,
      points: 100,
    },
    {
      id: 12,
      category: 'pattern',
      difficulty: 'easy',
      title: 'Fibonacci',
      description: 'Complete a sequência de Fibonacci:\n\n1  →  1  →  2  →  3  →  5  →  8  →  ___',
      hint: 'Cada número é a soma dos dois anteriores.',
      answer: '13',
      answerType: 'text',
      timeLimit: 45,
      points: 100,
    },
    {
      id: 13,
      category: 'pattern',
      difficulty: 'medium',
      title: 'Padrão de Letras',
      description: 'Qual é a próxima letra?\n\nA  →  C  →  F  →  J  →  O  →  ___',
      hint: 'Observe os saltos: +2, +3, +4, +5... qual é o próximo?',
      answer: 'u',
      answerType: 'text',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 14,
      category: 'pattern',
      difficulty: 'medium',
      title: 'Quadrados Perfeitos',
      description: 'Qual é o próximo número?\n\n1  →  4  →  9  →  16  →  25  →  ___',
      hint: '1², 2², 3², 4², 5², 6²...',
      answer: '36',
      answerType: 'text',
      timeLimit: 60,
      points: 200,
    },
    {
      id: 15,
      category: 'pattern',
      difficulty: 'hard',
      title: 'Números Primos',
      description: 'Qual é o próximo número?\n\n2  →  3  →  5  →  7  →  11  →  13  →  ___',
      hint: 'Números divisíveis apenas por 1 e por si mesmos.',
      answer: '17',
      answerType: 'text',
      timeLimit: 90,
      points: 300,
    },
  ],
  riddle: [
    {
      id: 16,
      category: 'riddle',
      difficulty: 'easy',
      title: 'Sem Vida',
      description: 'Tenho cidades sem casas,\nflorestas sem árvores\ne oceanos sem água.\n\nO que sou?',
      hint: 'Representa lugares, mas não é um lugar real.',
      answer: 'mapa',
      answerType: 'text',
      timeLimit: 60,
      points: 100,
    },
    {
      id: 17,
      category: 'riddle',
      difficulty: 'easy',
      title: 'Paradoxo',
      description: 'Quanto mais você me tira,\nmaior eu fico.\n\nO que sou?',
      hint: 'Pense em uma escavação no chão.',
      answer: 'buraco',
      answerType: 'text',
      timeLimit: 60,
      points: 100,
    },
    {
      id: 18,
      category: 'riddle',
      difficulty: 'medium',
      title: 'Dentes Inofensivos',
      description: 'Tenho dentes,\nmas não consigo morder.\n\nO que sou?',
      hint: 'Usado para organizar o cabelo.',
      answer: 'pente',
      answerType: 'text',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 19,
      category: 'riddle',
      difficulty: 'medium',
      title: 'Quanto Mais Seca...',
      description: 'Quanto mais me seco,\nmais molhada fico.\n\nO que sou?',
      hint: 'Usada logo após o banho.',
      answer: 'toalha',
      answerType: 'text',
      timeLimit: 90,
      points: 200,
    },
    {
      id: 20,
      category: 'riddle',
      difficulty: 'hard',
      title: 'Guarde Bem',
      description: 'Se você me tem, quer me compartilhar.\nSe me compartilha, já não me tem.\n\nO que sou?',
      hint: 'Algo que perde valor quando é revelado.',
      answer: 'segredo',
      answerType: 'text',
      timeLimit: 120,
      points: 300,
    },
  ],
};

export const CATEGORY_LABELS: Record<string, string> = {
  logic: 'LÓGICA',
  cipher: 'CIFRAS',
  pattern: 'PADRÕES',
  riddle: 'ENIGMAS',
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  logic: 'Raciocínio dedutivo e paradoxos',
  cipher: 'Códigos secretos e criptografia',
  pattern: 'Sequências e padrões matemáticos',
  riddle: 'Enigmas clássicos e metáforas',
};

export const CATEGORY_COLORS: Record<string, string> = {
  logic: 'cyan',
  cipher: 'green',
  pattern: 'yellow',
  riddle: 'pink',
};

export const CATEGORY_ICONS: Record<string, string> = {
  logic: '⬡',
  cipher: '⌘',
  pattern: '◈',
  riddle: '◉',
};
