import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  APP_NAME: z.string().min(1).default('A323 Plataforma Modular'),
  APP_URL: z.string().url().default('http://localhost:3000'),
  DATABASE_URL: z.string().min(1).default('postgresql://postgres:postgres@localhost:5432/a323'),
  SESSION_SECRET: z.string().min(32, 'SESSION_SECRET deve possuir ao menos 32 caracteres.'),
  STORAGE_DRIVER: z.enum(['local', 's3']).default('local'),
  STORAGE_LOCAL_PATH: z.string().default('./storage'),
  MODULE_STUDENTS: z.coerce.boolean().default(true),
  MODULE_GUARDIANS: z.coerce.boolean().default(true),
  MODULE_CLASSES: z.coerce.boolean().default(true),
  MODULE_ENROLLMENTS: z.coerce.boolean().default(true),
  MODULE_ATTENDANCE: z.coerce.boolean().default(true),
  MODULE_CONTENTS: z.coerce.boolean().default(false),
  MODULE_LESSON_PLANS: z.coerce.boolean().default(false),
  MODULE_EVALUATIONS: z.coerce.boolean().default(false),
  MODULE_EVENTS: z.coerce.boolean().default(false),
  MODULE_MESSAGING: z.coerce.boolean().default(false),
  MODULE_REPORTS: z.coerce.boolean().default(false),
  MODULE_MEDIA: z.coerce.boolean().default(false),
  MODULE_PSYCHOLOGY: z.coerce.boolean().default(false),
  MODULE_PRIVACY: z.coerce.boolean().default(true),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  APP_NAME: process.env.APP_NAME,
  APP_URL: process.env.APP_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  SESSION_SECRET: process.env.SESSION_SECRET ?? 'development-session-secret-with-32-chars',
  STORAGE_DRIVER: process.env.STORAGE_DRIVER,
  STORAGE_LOCAL_PATH: process.env.STORAGE_LOCAL_PATH,
  MODULE_STUDENTS: process.env.MODULE_STUDENTS,
  MODULE_GUARDIANS: process.env.MODULE_GUARDIANS,
  MODULE_CLASSES: process.env.MODULE_CLASSES,
  MODULE_ENROLLMENTS: process.env.MODULE_ENROLLMENTS,
  MODULE_ATTENDANCE: process.env.MODULE_ATTENDANCE,
  MODULE_CONTENTS: process.env.MODULE_CONTENTS,
  MODULE_LESSON_PLANS: process.env.MODULE_LESSON_PLANS,
  MODULE_EVALUATIONS: process.env.MODULE_EVALUATIONS,
  MODULE_EVENTS: process.env.MODULE_EVENTS,
  MODULE_MESSAGING: process.env.MODULE_MESSAGING,
  MODULE_REPORTS: process.env.MODULE_REPORTS,
  MODULE_MEDIA: process.env.MODULE_MEDIA,
  MODULE_PSYCHOLOGY: process.env.MODULE_PSYCHOLOGY,
  MODULE_PRIVACY: process.env.MODULE_PRIVACY,
});
